// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// qgcnt_iid
IntegerVector qgcnt_iid(NumericVector p, double lambda, double alpha);
RcppExport SEXP gammacount_qgcnt_iid(SEXP pSEXP, SEXP lambdaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(qgcnt_iid(p, lambda, alpha));
    return rcpp_result_gen;
END_RCPP
}
// qgcnt_one
int qgcnt_one(double p, double lambda, double alpha);
RcppExport SEXP gammacount_qgcnt_one(SEXP pSEXP, SEXP lambdaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(qgcnt_one(p, lambda, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rgcnt_one
int rgcnt_one(double lambda, double alpha);
RcppExport SEXP gammacount_rgcnt_one(SEXP lambdaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rgcnt_one(lambda, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rgcnt_iid
IntegerVector rgcnt_iid(int n, double lambda, double alpha);
RcppExport SEXP gammacount_rgcnt_iid(SEXP nSEXP, SEXP lambdaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rgcnt_iid(n, lambda, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rgnzp_esc
IntegerVector rgnzp_esc(int n, double lambda, double alpha);
RcppExport SEXP gammacount_rgnzp_esc(SEXP nSEXP, SEXP lambdaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rgnzp_esc(n, lambda, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rgnzp_vec
IntegerVector rgnzp_vec(int n, NumericVector lambda, NumericVector alpha);
RcppExport SEXP gammacount_rgnzp_vec(SEXP nSEXP, SEXP lambdaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rgnzp_vec(n, lambda, alpha));
    return rcpp_result_gen;
END_RCPP
}
