# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.rgnzp_esc <- function(n, lambda, alpha) {
    .Call('CountReg_rgnzp_esc', PACKAGE = 'CountReg', n, lambda, alpha)
}

.rgnzp_vec <- function(n, lambda, alpha) {
    .Call('CountReg_rgnzp_vec', PACKAGE = 'CountReg', n, lambda, alpha)
}

